//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wfVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_ingreso
    {
        public int iddetalle_ingreso { get; set; }
        public int idingreso { get; set; }
        public int idarticulo { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual ingreso ingreso { get; set; }
    }
}
